### PR TITLE
update flake inputs

### PR DESCRIPTION
**Pull request by ethancedwards8**
## Relevant Issues

None

## Description

Updates some nix sources to keep the package up to date

## Reasoning

This keeps the package secure and up to date

## Did you:

- [x] Join the [**Piston CLI Discord Community**](https://discord.gg/c7dZ4zdGQT)?
- [N/A] If dependencies have been added or updated, run `pipenv lock`?
- [N/A] **Lint your code** (`pipenv run lint`)?
- [x] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by ethancedwards8** [comment]
I'm not sure how to test the workflow.

**Comment by Shivansh-007** [comment]
> I'm not sure how to test the workflow.

You can test the workflow on your fork.

**Comment by Shivansh-007** [comment]
> I'm not sure how to test the workflow.

You can test the workflow on your fork, it should add those commits on the cron jobs, since there are no other restrictions that I can see.

Another comment is that, I think it should open a pull request rather than committing directly to main from a branch `update-flake-inputs`.

**Comment by ethancedwards8** [comment]
> > I'm not sure how to test the workflow.
> 
> You can test the workflow on your fork, it should add those commits on the cron jobs, since there are no other restrictions that I can see.
Figured it out. :)
> 
> Another comment is that, I think it should open a pull request rather than committing directly to main from a branch `update-flake-inputs`.

I think that committing directly to is fine. Because this *is* an unstable/development package. If users want to use the stable version of piston-cli, they should use the one from nixpkgs. Also, multiple other projects do this: https://github.com/nix-community/neovim-nightly-overlay and https://github.com/nix-community/emacs-overlay

**Review by Shivansh-007 — APPROVED** [review]

**Pull request merged**
