### PR TITLE
Initial Nix Support

### PR DESCRIPTION
**Pull request by ethancedwards8**
This has both flake and non-flake support:

default.nix and shell.nix are the non-flake support, these are vital
to building (default.nix) and developing (shell.nix) piston-cli.

Flakes are able to combine both into one file which is convenient.

Thanks to flake-compat we can just change the flake.nix and both the
default.nix and shell.nix will reflect those changes.

## Did you:

- [ ] Join the [**Piston CLI Discord Community**](https://discord.gg/c7dZ4zdGQT)?
- [ ] If dependencies have been added or updated, run `pipenv lock`?
- [ ] **Lint your code** (`pipenv run lint`)?
- [ ] Set the PR to **allow edits from contributors**?

### CODE REVIEW

**Comment by ethancedwards8** [comment]
I'm not sure why the lint check failed, as I didn't change any python files?

**Comment by Shivansh-007** [comment]
> I'm not sure why the lint check failed, as I didn't change any python files?

The lint is failing since there is no new line at the end of file in `.gitignore`. The pre-commit hooks run of the whole git repository other than the locations we have ignored in the configuration.

**Comment by ethancedwards8** [comment]
With that commit the PR is ready to be merged if you want it to be :)

**Review by MagicRB — CHANGES_REQUESTED** [review]
Looks fine to me, all builds and works, I only have 2 suggestions:
1. the `default.nix` and `shell.nix` should either be in the root of the repo or there should be symlinks pointing to them from the root
2. why not add the hydraJobs sections while we're at it, so that we can put it on some Hydra

**Comment by ethancedwards8** [comment]
> Looks fine to me, all builds and works, I only have 2 suggestions:
> 
>     1. the `default.nix` and `shell.nix` should either be in the root of the repo or there should be symlinks pointing to them from the root
> 
>     2. why not add the hydraJobs sections while we're at it, so that we can put it on some Hydra

1. @Shivansh-007  didn't want all those files in the root of the repo. So we compromised and moved them to the packaging dir. 

2. Sure, what should I put?

**Comment by Shivansh-007** [comment]
> 1. @Shivansh-007  didn't want all those files in the root of the repo. So we compromised and moved them to the packaging dir. 

The reason being mainly, that I don't think it would be included in the package, but I think am wrong, it should be included in the package since even the poetry files do (I guess) not sure. I will verify myself and get back.

**Comment by MagicRB** [comment]
>     2. Sure, what should I put? Or you can create a PR directly on my repo.

```nix
let
  forAllSystems = f: forAllSystems' supportedSystems f;
  forAllSystems' = systems: f: nixpkgs.lib.genAttrs systems (system: f system); 
in
{
  # ...

  
  hydraJobs = forAllSystems' [ "x86_64-linux" ] (system: {
    build = self.defaultPackage.${system};
  });
}
```
because my Hydra can only build `x86_64-linux` as of now. Add it and then I'll add your fork to my Hydra to see whether it builds, then we can merge.

**Comment by ethancedwards8** [comment]
The build passes. https://hydra.redalder.org/project/piston-cli 

I think leaving the shell.nix and default.nix in the packaging dir is fine, as they still function as expected. A lot of projects do this, for example, veloren. https://gitlab.com/veloren/veloren

**Comment by Shivansh-007** [comment]
Alright, @MagicRB could you give it another review :)

**Comment by MagicRB** [comment]
Looks fine to me and Hydra.

**Review by Shivansh-007 — APPROVED** [review]
On behalf of @MagicRB

**Comment by MagicRB** [comment]
I'll retarget Hydra

**Pull request merged**
